# This is a basic workflow to help you get started with Actions

name: CI

env:
  DEPLOY_VER: ${{ github.sha }} 
  YEAR      : "2022"

on:
  workflow_dispatch:

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:    
 
      - name: Git clone 
        uses: actions/checkout@v1
 
      - name: Print the list of files/directories 
        run: ls -a

      - name: Print content of log.txt file.
        run: cat Task1/log.txt
  
      - name: Print Hello from 
        run:  echo “Hello from ${{ env.DEPLOY_VER }} commit”
     
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
#   env:
#     month: january
    
    steps:  
#       - name: Contain day of the month
#         env:
#           DAY__OF_THE_MONTH: Monday
 
        - name: Print the system date and time 
          run: date

#       - name: Print day, month, year
#         run:|
#           echo " Day - $DAY__OF_THE_MONTH"
#           echo "Month -$month"
#           echo  "Year - ${{ env.YEAR }}"
 
#       - name: Print “My favorite day of week"
#         run:  echo "My favorite day of week is “content of FAVORITE_DAY_OF_WEEK””
